---
- name: install packages
  become: true
  become_method: enable 
  ansible.builtin.package:
    state: present
    name:
         - vim
         - tmux
         - lynx
         - wmctrl
         - bash-completion
         - curl
         - wget
         - git
         - python3
         - htop
         - moreutils
         - sxhkd
         - htop
         - fzf
         - ripgrep
         - bat
         - w3m
- name: install i3
  become: true
  become_method: enable
  ansible.builtin.package:
    state: present
    name:
          - i3
          - i3lock-color
          - i3blocks
