# Setup a Python 3.8 virtual environment
#
- name: Install virtualenv
  pip: name={{ item }}
  with_items:
    - virtualenv

- name: Setup an environment for basic python testing
  shell: virtualenv -p /opt/python3.8/bin/python3.8 ~/python3_testing

- name: Install packages required for basic python datascience
  pip: name={{ item }} virtualenv="~/python3_testing"
  with_items: 
    - python-dateutil
    - scipy
    - matplotlib
    - scikit-learn
    - plotly
    - jupyter


