#!/bin/sh
# This setup script takes all the rc files stored in this .dotfiles and symlinks them to their correct location in the system. Further to this it appends the scripts folder which is aliased to ~/.local/bin/scripts to path. By doing this we are able to make use of all the scripts developed by rwxrob and can use scripts such as newx to create our own scripts which are automatically added to this location. 

set -e 


pathappend() {
  for ARG in "$@"; do
    test -d "${ARG}" || continue
    case ":${PATH}:" in
    *:${ARG}:*) continue ;;
    esac
    export PATH="${PATH:+"${PATH}:"}${ARG}"
    echo "$PATH"
  done
}

create_scripts_links() {
    export SCRIPTS=~/.local/bin/scripts
    test ! -d "$SCRIPTS" && mkdir -p "$SCRIPTS"
    ln -sf "$PWD/scripts" "$HOME/.local/bin/scripts"

    echo "adding scripts to path"
    if test -e ~/.bashrc-personal; then
        echo "bashrc found"
        pathappend \
            "$SCRIPTS/"
    fi
}

git_update() {
    
# make sure we have pulled in and updated any submodules
    echo "Updating git submodules"
    git submodule init  >>/dev/null
    git submodule update >>/dev/null
    echo "Submodules Updated"
}


set_symlinks() {

    # Create symlinks.
    echo "Creating Symlinks"
    # Bash Configs
    ln -sf "$PWD/bash/bashrc" "$HOME/.bashrc-personal"
    ln -sf "$PWD/.profile" "$HOME/.bash_profile"

    ln -sf "$PWD/.dircolors" "$HOME/.dircolors"

    #vimrc
    ln -sf "$PWD/nvim/nvim" "$HOME/.config/nvim"
    
    
    #Xmonad Configs
    ln -sf "$PWD/xmonad/.xmonad" "$HOME/.config/.xmonad/xmonad.hs"
    ln -sf "$PWD/xmobar/xmobar" "$HOME/.config/xmobar"

}



main() {
# make sure we have pulled in and updated any submodules
#Create scripts directory in .local/bin and symlink the scripts folder
    echo "Start installation of dotfiles and scripts"
    git_update
    set_symlinks
    create_scripts_links
    
    echo ""
    echo "##### ALL DONE"
}


git_update
