#!/bin/sh


# This setup script takes all the rc files stored in this .dotfiles and symlinks them to their correct location in the system. Further to this it appends the scripts folder which is aliased to ~/.local/bin/scripts to path. By doing this we are able to make use of all the scripts developed by rwxrob and can use scripts such as newx to create our own scripts which are automatically added to this location. 

set -e 


pathappend() {
  for ARG in "$@"; do
    test -d "${ARG}" || continue
    case ":${PATH}:" in
    *:${ARG}:*) continue ;;
    esac
    export PATH="${PATH:+"${PATH}:"}${ARG}"
    echo "$PATH"
  done
}

create_scripts_links() {
    
    echo "Setting Scripts variable and adding scripts to path"
    if test -f ~/.bashrc-personal; then
        if ! grep -q SCRIPTS ~/.bashrc-personal; then
	    echo "SCRIPTS doesn't exist adding it now."
	    export SCRIPTS=~/.local/bin/scripts
	fi
    fi

    test ! -d "$SCRIPTS" && mkdir -p "$SCRIPTS"
    ln -sf "$PWD/scripts" "$HOME/.local/bin/scripts"

    echo "adding scripts to path"
    if test -e ~/.bashrc-personal; then
        echo "bashrc found"
        pathappend \
            "$SCRIPTS/"
    fi
}

git_update() {
    
# make sure we have pulled in and updated any submodules
    echo "Updating git submodules"
    git submodule init  >>/dev/null
    git submodule update >>/dev/null
    echo "Submodules Updated"
}


set_symlinks() {

    # Create symlinks.
    echo "Creating Symlinks"
    DOT=$HOME/repos/github.com/qwertimer/.dotfiles
    argc="$@"
    for arg in $argc; do
	x=$arg
        case $x in
	
        -bash | bash)
	    BASH_FOLDER=$HOME 
            echo "Adding bash to $BASH_FOLDER"
	    echo "-------------------"
            ln -sf "$DOT/bash/.bashrc" "$BASH_FOLDER/.bashrc"
            ln -sf "$DOT/bash/.bashrc-common" "$BASH_FOLDER/.bashrc-common"
            ln -sf "$DOT/bash/.bashrc-personal" "$BASH_FOLDER/.bashrc-personal"
            ln -sf "$DOT/.profile" "$BASH_FOLDER/.bash_profile"     #replace with home
        ;;

        -dc | dir-col)
	    DIR_FOLDER=$HOME
	    echo "Adding dir colors to $DIR_FOLDER"

	    echo "-------------------"
            ln -sf "$DOT/.dircolors" "$DIR_FOLDER/.dircolors"
     
        ;;
        -tmux | tmux)
	    TMUX_FOLDER=$HOME
            echo "Adding TMUX to $TMUX_FOLDER"
	    echo "-------------------"
            ln -sf "$DOT/tmux/tmux/tmux.conf" "$TMUX_FOLDER/.tmux.conf"   

        ;;
        -vim | vim)

	    VIM_FOLDER=$HOME/.vim/
	    echo "Adding vim config to $VIM_FOLDER"
	    echo "-------------------"
            ln -sf "$DOT/vim/" "$VIM_FOLDER"   #.config/nvim"
            ln -sf "$DOT/vim/.vimrc" "$HOME/.vimrc"


        ;;
        -nvim | nvim)
	    NVIM_FOLDER=$HOME/.config/
	    echo "Adding vim config to $NVIM_FOLDER"
	    echo "-------------------"
            ln -sf "$DOT/nvim/" "$NVIM_FOLDER/nvim"   #.config/nvim"
        
        ;;
        #Xmonad Configs
        -xmonad | xmonad)
	    XMONAD_FOLDER=$HOME/.config/.xmonad
	    XMOBAR_FOLDER=$HOME/.config/xmobar
            echo "Adding xmonad config to $XMONAD_FOLDER"
	    echo "-------------------"
            ln -sf "$DOT/.xmonad/" "$XMONAD_FOLDER"

	    echo "Adding xmobarrc to $XMOBAR_FOLDER"
	    echo "-------------------"
            ln -sf "$DOT/xmobar/xmobar" "$XMOBAR_FOLDER"

        ;;
        -zsh | zsh)

	    ZSH_FOLDER=$HOME
	    echo "Adding ZSH config to $ZSH_FOLDER"
	    echo "-------------------"
            ln -sf "$DOT/zsh/zshrc" "$ZSH_FOLDER/.zshrc"
        ;;

        -all | all)
	    echo "-------------------"
	    echo "Add all"

	    BASH_FOLDER=$HOME 
            echo "Adding bash to $BASH_FOLDER"
	    echo "-------------------"
            ln -sf "$DOT/bash/.bashrc" "$BASH_FOLDER/.bashrc"
            ln -sf "$DOT/bash/.bashrc-common" "$BASH_FOLDER/.bashrc-common"

	    echo "$DOT/bash/bashrc"
            ln -sf "$DOT/bash/.bashrc-personal" "$BASH_FOLDER/.bashrc-personal"
            ln -sf "$DOT/bash/.bash_profile" "$BASH_FOLDER/.bash_profile"     #replace with home
	    
	    DIR_FOLDER=$HOME
	    echo "Adding dir colors to $DIR_FOLDER"
	    echo "-------------------"
            ln -sf "$DOT/.dircolors" "$DIR_FOLDER/.dircolors"

	    TMUX_FOLDER=$HOME
            echo "Adding TMUX to $TMUX_FOLDER"
	    echo "-------------------"
            ln -sf "$DOT/tmux/tmux/tmux.conf" "$TMUX_FOLDER/.tmux.conf"   


	    VIM_FOLDER=$HOME/.vim/
	    echo "Adding vim config to $VIM_FOLDER"
	    echo "-------------------"
            ln -sf "$DOT/vim/" "$VIM_FOLDER"   
            ln -sf "$DOT/vim/.vimrc" "$HOME/.vimrc"

	    NVIM_FOLDER=$HOME/.config
	    echo "Adding vim config to $NVIM_FOLDER"
	    echo "-------------------"
            ln -sf "$DOT/nvim" "$NVIM_FOLDER/nvim"   
        
	    XMONAD_FOLDER=$HOME/.config
	    XMOBAR_FOLDER=$HOME/.config
            echo "Adding xmonad config to $XMONAD_FOLDER"
	    echo "-------------------"
            ln -sf "$DOT/.xmonad/" "$XMONAD_FOLDER"

	    echo "Adding xmobarrc to $XMOBAR_FOLDER"
	    echo "-------------------"
	    test -d "$DOT/xmobar/" || mkdir "$DOT/xmobar"
            ln -sf "$DOT/xmobar/" "$XMOBAR_FOLDER/"

	    ZSH_FOLDER=$HOME
	    echo "Adding ZSH config to $ZSH_FOLDER"
	    echo "-------------------"
            ln -sf "$DOT/zsh/zshrc" "$ZSH_FOLDER/.zshrc"

        esac
    done
}

add_lynx() {
#Lynx can be installed locally with Robs configs, or using a dockerfile can help improve usability. The method here checks for a lynx program in 
echo "hello"
}

main() {
# make sure we have pulled in and updated any submodules
#Create scripts directory in .local/bin and symlink the scripts folder
    echo "Start installation of dotfiles and scripts"
    #git_update
    set_symlinks "$@"
    create_scripts_links 
    
    echo ""
    echo "##### ALL DONE"
}

main "$@"
