---
- hosts: all

  tasks:

    - name: Create New Volume
      community.docker.docker_volume:
        name: portainer-data

    - name: Deploy Portainer
      community.docker.docker_container:
        name: portainer
        image: "docker.io/portainer/portainer-ce"
        ports:
          - "9000:9000"
          - "8000:8000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer-data:/data
        restart_policy: always

    - name: Deploy Watchtower
      community.docker.docker_container:
        name: watchtower
        image: containrrr/watchtower
        command: --schedule "0 0 4 * * *"        # Schedule for 5 am
        volumes:
          /var/run/docker.sock:/var/run/docker.sock
        restart_policy: always
