---
- hosts: surface
  become: yes
  tasks:
  - name: Deploy Traefik
    become_user: "{{ lookup('env','USER') }}"
    community.docker.docker_container:
      name: traefik
      image: "traefik:v2.5"
      ports:
        - "1080:80"
        - "9443:443"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /etc/traefik:/etc/traefik
      restart_policy: always
