#!/bin/bash
export C_Red='\e[2;31m';       C_BRed='\e[1;31m';      C_Green='\e[2;32m';  \
C_BGreen='\e[1;32m';    C_Yellow='\e[2;33m';    C_BYellow='\e[1;33m'; \
C_Grey='\e[2;37m';      C_Reset='\e[0m';        C_BPink='\e[1;35m';   \
C_Italic='\e[3m';       C_Blue='\e[2;34m';      C_BBlue='\e[1;34m';   \
C_Pink='\e[2;35m';      C_Cyan='\e[2;36m';      C_BCyan='\e[1;36m'i;  \

#Simple modifiers
C_Blink='\e[6m';        C_Under='\e[4m'         C_Italic='\e[3m'}
