#!/bin/bash
# ------------------------------ bash completion -----------------------------

##Must be placed below the functions

IFS=$'\n'
functions=()
for f in $(declare -F); do
  functions+=( $f )
done
func_pre=_

declare -a COMMANDS="${functions[@]//declare -f $func_pre}"
if [[ -n $COMP_LINE ]]; then

    for c in "${COMMANDS[@]}"; do
        [[ ${c:0:${#2}} == "${2,,}" ]] && echo "$c"
    done
fi


### Robs Mods to my code
#while read -r line; do
#  [[ $line =~ ^declare\ -f\ _ ]] || contine
#  COMMANDS+=( ${line##declare -f _} )
#done < <(declare -F)
#
#
#if [[ -n $COMP_LINE ]]; then
#
#    for c in "${COMMANDS[@]}"; do
#        [[ ${c:0:${#2}} == "${2,,}" ]] && echo "$c"
#    done
#fi
