#!/bin/bash

DIR=`mktemp -d`
REPOS="git@github.com:qwertimer/.dotfiles.git"
BRANCH="master"
CHECKOUT_DIR="scripts/"

mkdir -p $DIR
echo $DIR >&2
if [ -d "$DIR" ]; then
  cd $DIR
  git init
  git remote add -f origin $REPOS
  git fetch --all --filter=blob:none 
  git config core.sparseCheckout true
  if [ -f .git/info/sparse-checkout]; then
    rm .git/info/sparse-checkout
  fi
  echo !**/*\n$CHECKOUT_DIR >> .git/info/sparse-checkout
  git checkout $BRANCH
  git merge --ff-only origin/$BRANCH
fi
