#!/bin/bash
declare -a help

# Author: Conner McDaniel
# https://github.com/connermcd/bin
# MIT license


set -e

main() {
    result=
    i=
    while [[ $i -lt 10 && "$result" != *"author = "* ]]; do
        result=$(curl -s "http://api.crossref.org/works/$1/transform/application/x-bibtex")
        i=$(( $i + 1 ))
    done
    echo "$result"
}


help() {
   help[description]="gets the doi and searches for the bibtex citation on
   crossref."

   echo "gets the doi and searches for the bibtex citation on crossref."
}

case $@ in
    -h)
        help
        ;;
    *)
        main $@
        ;;
esac



