#!/bin/bash
git clone --bare git@github.com:qwertimer/dotfiles $HOME/.cfg

bare() {
   /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME $@
}


mkdir -p .config-backup
bare checkout
if [ $? = 0 ]; then
  echo "Checked out config.";
  else
    echo "Backing up pre-existing dot files.";
    bare checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .config-backup/{}
fi;
bare checkout
bare config status.showUntrackedFiles no
