#!/bin/bash

options=("alacritty
bspwm
bash
dunst
picom
polybar
sxhkd
vim
xresources
quit")

#choice=$(echo -e "${options[@]}" | dmenu -g 5 -l 10 -fn 'Monaco' -p 'Edit config file: ' -nb '#222222' -nf '#b8b8b8' -sb '#181818' -sf '#10713c')
choice=$(echo -e "${options[@]}" | rofi -dmenu -p 'Edit config file: ')

case "$choice" in
    quit)
        echo "Program terminated." && exit 1
        ;;
    alacritty)
        choice="$HOME/.config/alacritty.yml"
        ;;
    bash)
        choice="$HOME/.bashrc"
        ;;
    bspwm)
        choice="$HOME/.config/bspwm/bspwmrc"
        ;;
    dunst)
        choice="$HOME/.config/dunst/dunstrc"
        ;;
    picom)
        choice="$HOME/.config/picom/picom.conf"
        ;;
    polybar)
        choice="$HOME/.config/polybar/config"
        ;;
    sxhkd)
        choice="$HOME/.config/sxhkd/sxhkdrc"
        ;;
    vim)
        choice="$HOME/.vimrc"
        ;;
    xresources)
        choice="$HOME/.Xresources"
        ;;
    *)
        exit 1
        ;;
esac
kitty -e vim "$choice"


