#!/bin/bash

# Developed by Qwertimer.
# Simple command line utility to take new commands that you don't know
# and learn their usage from explainshell.com

if [ "$#" -eq 0 ]; then
  while read  -p "Command: " cmd; do
    xdg-open "https://explainshell.com/explain?cmd=$cmd"
  done
  echo "Bye!"
elif [ "$#" -eq 1 ]; then
  xdg-open "https://explainshell.com/explain?cmd=$1"
else
  echo "Usage"
  echo "explain 'Interactive tool'"
  echo "explain 'cmd -o | ...'   one quoted command to explain it."
fi
