#!/bin/bash
# sudo apt install jq wget curl
# usage: github-install user/repo
set -e
r=$1
repo=$1
tmp="/tmp/.github-install"
binpath="$HOME/.local/bin"

# get filename
OLDIFS=$IFS
IFS='/'
read -a str <<< $r
f="${str[1]}"
IFS=$OLDIFS

rm -rf $tmp
mkdir -p $tmp
url="https://api.github.com/repos/$1/releases/latest"
echo "Reading... $url"

PS3="Select download file: "
select filename in $(curl -s $url | jq -r '.assets[].name' | grep -i 'linux'); do break; done
    
echo "Downloading... $filename"
curl -s $url | jq -r --arg filename "$filename" '.assets[] | select(.name == $filename) | .browser_download_url' | wget -i- -q --show-progress -P "$tmp"

# extract
extract () {
    for arg in $@ ; do
        if [ -f $arg ] ; then
            case $arg in
                *.tar.bz2)  tar xjf $arg      ;;
                *.tar.gz)   tar xzf $arg      ;;
                *.tar.xz)   tar xzf $arg      ;;
                *.bz2)      bunzip2 $arg      ;;
                *.gz)       gunzip $arg       ;;
                *.tar)      tar xf $arg       ;;
                *.tbz2)     tar xjf $arg      ;;
                *.tgz)      tar xzf $arg      ;;
                *.zip)      unzip $arg        ;;
                *.Z)        uncompress $arg   ;;
                *.rar)      rar x $arg        ;;  # 'rar' must to be installed
                *.jar)      jar -xvf $arg     ;;  # 'jdk' must to be installed
                *)          echo "'$arg' cannot be extracted via extract()" ;;
            esac
        else
            echo "'$arg' is not a valid file"
        fi
    done
}

pushd $tmp
extract $filename

bin=$(find . -type f | grep "$f" | grep -v 'tar'| sed 's|^./||')
echo $bin
popd

# install
basename=$(basename $bin)
target="$binpath/${alias:-$basename}"
mv "$tmp/$bin" "$target"
chmod +x "$target"
echo "Success!"
echo "Saved in: $target"
