#!/bin/bash

# Created By: Qwertimer
# Created On: "Fri 11 Nov 2022 13:40:40 ACDT"
# Project: Go linter

docker run -it -v $(pwd):$(pwd) --workdir=$(pwd) --entrypoint "golangci-lint" golangci/golangci-lint:v1.51.1 $@
