#!/bin/sh
docker run -d \
  --name=plex \
  --net=host \
  -e PUID=1000 \
  -e PGID=1000 \
  -e VERSION=docker \
  -e PLEX_CLAIM= `#optional` \
  -v home/tim/library:/config \
  -v home/tim/tvseries:/tv \
  -v home/tim/plex/movies:/movies \
  --restart unless-stopped \
  lscr.io/linuxserver/plex
