#!/bin/bash

# Description: Gets the doi of a pdf.

# Author: Conner McDaniel
# https://github.com/connermcd/bin
# MIT license

set -e

pdftotext "$1" - | grep -oP "\b(10[.][0-9]{4,}(?:[.][0-9]+)*/(?:(?![\"&\'<>])\S)+)\b" | head -n 1
