#!/bin/bash

notification(){
	
	notify-send "Now Playing:"$1" Radio ☕️🎶"

}

options=("Lofi Girl
Chillhop
Box Lofi
The Bootleg Boy
Radio Spinner
SmoothChill
Rob
Hope 103.2 
Hope Christmas
Christmas Songs
Christmas Lofi")

choice=$(echo -e "${options[@]}" | rofi -dmenu -p 'Play songs:' )

pkill mpv 
name="${choice}"
notification "$name"
echo "$choice"
case "$choice" in
	  quit)
			echo "Terminated" && exit 1
			;;
		"Lofi Girl")
			mpd "https://play.streamafrica.net/lofiradio"
			;;
		Chillhop)
			mpv "http://stream.zeno.fm/fyn8eh3h5f8uv"
			;;
	  "Box Lofi")
			mpv "http://stream.zeno.fm/f3wvbbqmdg8uv"
			;;
		"The Bootleg Boy")
			mpv "http://stream.zeno.fm/0r0xa792kwzuv"
			;;
		"Radio Spinner")
			mpv "https://live.radiospinner.com/lofi-hip-hop-64"
			;;
		SmoothChill)
			mpv "https://media-ssl.musicradio.com/SmoothChill"
			;;
		Rob)
		  mpv "https://www.twitch.tv/rwxrob" --no-video
			;;
		"Hope 103.2")
			mpv "https://stream.hopemedia.com.au/hope-mp3" >/dev/null
			;;
			
		"Hope Christmas")
			mpv "https://stream.hopemedia.com.au/christmashope-mp3"
		  ;;
			
	"Christmas Songs")
			mpv "https://www.youtube.com/watch?v=NUtBQiKa-WU" --no-video
			;;

  "Christmas Lofi")
			mpv "https://www.youtube.com/watch?v=75LR1d9_mtM" --no-video >/dev/null &
			;;
		*)
			exit 1
			;;
esac

