#!/bin/bash


#This script is a quick getup and going for the github integrated issue based task manager of mine. The commands that are used are simple and easy to work with and are seen in this scripts folder.
#To work with the scripts a couple of setups are needed. We first must create the tasks folder which is located inside the repos/github directory. Once the folder is created we can initialise the repository and either git pull the current tasks repository or begin a new repository. The scripts below are setup to allow either approach. The script also gets and pulls my newtask, closetask and listtasks scripts and places them in the scripts folder.
GHREPO="$HOME"/repos/github.com/"$USER"/

init_scripts_folder() {
  mkdir -p "$GHREPO"/.dotfiles/scripts
  export SCRIPTS="$GHREPO"/.dotfiles/scripts
}


get_scripts() {
  if [ -d "$SCRIPTS" ]; then

    curl "https://raw.githubusercontent.com/qwertimer/.dotfiles/master/scripts/listtasks" > "$SCRIPTS"/listtasks
    curl "https://raw.githubusercontent.com/qwertimer/.dotfiles/master/scripts/newtask" > "$SCRIPTS"/newtask
    curl "https://raw.githubusercontent.com/qwertimer/.dotfiles/master/scripts/closetask" > "$SCRIPTS"/closetask
  else 
    init_scripts_folder
  fi
}

init_task_folder() {
  mkdir -p "$GHREPO"/"$1"
  cd "$GHREPO"/"$1"
  git init
  touch README.md
  echo "You will now need to run the command to add the repo to github using 
    `gh repo create` and follow the instructions. Once completed add the README.md file to 
    repo with `git add .` `git commit -m "new README.md"` `git push -u origin master`."

}

add_bash_aliases() {
  { echo 'alias st=listtasks';  echo 'alias nt=newtask'; echo 'alias ct=closetask'; } >> ~/.bashrc

}


main() {

  get_scripts
  init_task_folder "$1"
  add_bash_aliases

}
