#!/bin/bash


# Created By: Qwertimer
# Created On: "Thu 26 Jan 2023 23:13:31 ACDT"
# Project:
#
youtube-dl --ignore-errors --format bestaudio --extract-audio --audio-format mp3 --audio-quality 160K --output "%(title)s.%(ext)s" --yes-playlist https://www.youtube.com/playlist?list="$1"
