#!/bin/sh

: "${tmplist="/tmp/tmplist"}"
file=`mktemp`

while IFS= read -r line; do
    echo "$line" >> "$file"
    echo "$line"
done
#copy to xclip for pasting elsewhere

echo "$file" >> "$tmplist"
cat "$file" | xclip
